TARGET_COMPANIES = [
    {
        "name": "Ramp",
        "source": "ashby",
        "board_token": "ramp",
        "category": "fintech_risk",
    },
    {
        "name": "SentiLink",
        "source": "ashby",
        "board_token": "sentilink",
        "category": "fintech_risk",
    },
    {
        "name": "Cardless",
        "source": "ashby",
        "board_token": "cardless",
        "category": "fintech_risk",
    },
    {
        "name": "Two Dots",
        "source": "ashby",
        "board_token": "two-dots",
        "category": "fintech_risk",
    },
    {
        "name": "Numeral",
        "source": "ashby",
        "board_token": "numeral",
        "category": "fintech",
    },
    {
        "name": "Sapiom",
        "source": "ashby",
        "board_token": "sapiom",
        "category": "ai_fintech",
    },
    {
        "name": "Quora",
        "source": "ashby",
        "board_token": "quora",
        "category": "ai",
    },
    {
        "name": "Netic",
        "source": "ashby",
        "board_token": "netic",
        "category": "ai",
    },
    {
        "name": "Foxglove",
        "source": "ashby",
        "board_token": "foxglove",
        "category": "data_ai",
    },
    {
        "name": "Genmo",
        "source": "ashby",
        "board_token": "genmo",
        "category": "ai",
    },
    {
        "name": "Harvey",
        "source": "ashby",
        "board_token": "harvey",
        "category": "ai",
    },
    {
        "name": "Dave",
        "source": "ashby",
        "board_token": "dave",
        "category": "fintech",
    },
    {
        "name": "Stripe",
        "source": "greenhouse",
        "board_token": "stripe",
        "category": "fintech",
    },
    {
        "name": "Databricks",
        "source": "greenhouse",
        "board_token": "databricks",
        "category": "data_ai",
    },
    {
        "name": "Robinhood",
        "source": "greenhouse",
        "board_token": "robinhood",
        "category": "fintech",
    },
    {
        "name": "Affirm",
        "source": "greenhouse",
        "board_token": "affirm",
        "category": "fintech",
    },
    {
        "name": "Coinbase",
        "source": "greenhouse",
        "board_token": "coinbase",
        "category": "crypto_fintech",
    },
    {
        "name": "Chime",
        "source": "greenhouse",
        "board_token": "chime",
        "category": "fintech",
    },
    {
        "name": "Brex",
        "source": "greenhouse",
        "board_token": "brex",
        "category": "fintech",
    },
    {
        "name": "Instacart",
        "source": "greenhouse",
        "board_token": "instacart",
        "category": "marketplace",
    },
    {
        "name": "Airbnb",
        "source": "greenhouse",
        "board_token": "airbnb",
        "category": "marketplace",
    },
    {
        "name": "Mercury",
        "source": "greenhouse",
        "board_token": "mercury",
        "category": "fintech",
    },
    {
        "name": "Datadog",
        "source": "greenhouse",
        "board_token": "datadog",
        "category": "data_infra",
    },
    {
        "name": "Lyft",
        "source": "greenhouse",
        "board_token": "lyft",
        "category": "marketplace",
    },
    {
        "name": "Okta",
        "source": "greenhouse",
        "board_token": "okta",
        "category": "security",
    },
    {
        "name": "Scale AI",
        "source": "greenhouse",
        "board_token": "scaleai",
        "category": "ai",
    },
    {
        "name": "Anthropic",
        "source": "greenhouse",
        "board_token": "anthropic",
        "category": "ai",
    },
    {
        "name": "Figma",
        "source": "greenhouse",
        "board_token": "figma",
        "category": "productivity",
    },
    {
        "name": "Asana",
        "source": "greenhouse",
        "board_token": "asana",
        "category": "productivity",
    },
    {
        "name": "Airtable",
        "source": "greenhouse",
        "board_token": "airtable",
        "category": "productivity",
    },
    {
        "name": "MongoDB",
        "source": "greenhouse",
        "board_token": "mongodb",
        "category": "data_infra",
    },
    {
        "name": "Amplitude",
        "source": "greenhouse",
        "board_token": "amplitude",
        "category": "data_infra",
    },
    {
        "name": "Twilio",
        "source": "greenhouse",
        "board_token": "twilio",
        "category": "platform",
    },
    {
        "name": "Reddit",
        "source": "greenhouse",
        "board_token": "reddit",
        "category": "consumer_platform",
    },
    {
        "name": "Cloudflare",
        "source": "greenhouse",
        "board_token": "cloudflare",
        "category": "security",
    },
    {
        "name": "Duolingo",
        "source": "greenhouse",
        "board_token": "duolingo",
        "category": "consumer_platform",
    },
    {
        "name": "Gusto",
        "source": "greenhouse",
        "board_token": "gusto",
        "category": "fintech",
    },
    {
        "name": "LaunchDarkly",
        "source": "greenhouse",
        "board_token": "launchdarkly",
        "category": "developer_tools",
    },
    {
        "name": "Maven Clinic",
        "source": "greenhouse",
        "board_token": "mavenclinic",
        "category": "healthtech",
    },
    {
        "name": "Postman",
        "source": "greenhouse",
        "board_token": "postman",
        "category": "developer_tools",
    },
    {
        "name": "Samsara",
        "source": "greenhouse",
        "board_token": "samsara",
        "category": "iot_data",
    },
    {
        "name": "Vercel",
        "source": "greenhouse",
        "board_token": "vercel",
        "category": "developer_tools",
    },
    {
        "name": "Workato",
        "source": "greenhouse",
        "board_token": "workato",
        "category": "automation",
    },
    {
        "name": "ZoomInfo",
        "source": "greenhouse",
        "board_token": "zoominfo",
        "category": "data_platform",
    },
    {
        "name": "SoFi",
        "source": "greenhouse",
        "board_token": "sofi",
        "category": "fintech",
    },
    {
        "name": "Upstart",
        "source": "greenhouse",
        "board_token": "upstart",
        "category": "fintech_risk",
    },
    {
        "name": "Nubank",
        "source": "greenhouse",
        "board_token": "nubank",
        "category": "fintech",
    },
    {
        "name": "Adyen",
        "source": "greenhouse",
        "board_token": "adyen",
        "category": "fintech",
    },
    {
        "name": "GoFundMe",
        "source": "greenhouse",
        "board_token": "gofundme",
        "category": "marketplace",
    },
    {
        "name": "Plaid",
        "source": "lever",
        "board_token": "plaid",
        "category": "fintech",
    }
]
